export const CREATE_STUDENT = 'CREATE_STUDENT';
export const DETAIL_STUDENTS = 'RETRIEVE_STUDENTS';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_ALL_STUDENTS = 'DELETE_ALL_STUDENTS';
export const GET_LIST_STUDENT = 'GET_LIST_STUDENT';
